openapi: 3.0.3
info:
  title: Hex Presence Progression API
  version: 0.1.0
paths:
  /presence/{playerId}:
    get:
      summary: List presence records for player
      parameters:
        - in: path
          name: playerId
          required: true
          schema: { type: string }
        - in: query
          name: includeValues
          schema: { type: boolean, default: false }
      responses:
        '200':
          description: Player presence list
          content:
            application/json:
              schema:
                type: object
                properties:
                  entries:
                    type: array
                    items:
                      type: object
                      properties:
                        hexId: { type: string }
                        tierId: { type: integer }
                        value: { type: integer }
                  count: { type: integer }
        '404': { description: Player not found }
  /presence/{playerId}/{hexId}:
    get:
      summary: Get presence details for one hex
      parameters:
        - in: path
          name: playerId
          required: true
          schema: { type: string }
        - in: path
          name: hexId
          required: true
          schema: { type: string }
      responses:
        '200':
          description: Presence record
          content:
            application/json:
              schema:
                type: object
                properties:
                  playerId: { type: string }
                  hexId: { type: string }
                  value: { type: integer }
                  tierId: { type: integer }
                  decayState: { type: string }
                  lastVisitedAt: { type: string, format: date-time }
        '404': { description: Record not found }
  /presence/{playerId}/timeline/{hexId}:
    get:
      summary: Get recent presence timeline (if retained)
      parameters:
        - in: path
          name: playerId
          required: true
          schema: { type: string }
        - in: path
          name: hexId
          required: true
          schema: { type: string }
        - in: query
          name: windowHours
          schema: { type: integer, default: 24 }
      responses:
        '200':
          description: Timeline samples
          content:
            application/json:
              schema:
                type: object
                properties:
                  hexId: { type: string }
                  samples:
                    type: array
                    items:
                      type: object
                      properties:
                        ts: { type: string, format: date-time }
                        value: { type: integer }
        '404': { description: Record not found }
components:
  schemas:
    PresenceEntry:
      type: object
      properties:
        hexId: { type: string }
        value: { type: integer }
        tierId: { type: integer }
